
---

##  SQL  **FULL OUTER JOIN**

###  What is a FULL OUTER JOIN?

A **FULL OUTER JOIN** returns **all records from both tables**, whether or not there is a match.
If a row in one table **doesnâ€™t have a match in the other**, the result will contain `NULL` values on the side with no match.

> **Note:** MySQL does **not** support FULL OUTER JOIN directly. But you can emulate it using `UNION`.

---

###  Syntax (Standard SQL â€” if supported):

```sql
SELECT columns
FROM left_table
FULL OUTER JOIN right_table
ON left_table.common_column = right_table.common_column;
```

---

###  Not Supported in MySQL â€” Workaround with UNION

```sql
SELECT
    o.order_id,
    o.customer_id,
    oi.product_id,
    oi.quantity
FROM orders o
LEFT JOIN order_items oi
ON o.order_id = oi.order_id

UNION

SELECT
    o.order_id,
    o.customer_id,
    oi.product_id,
    oi.quantity
FROM orders o
RIGHT JOIN order_items oi
ON o.order_id = oi.order_id;
```

 **Explanation**:

* The first query gives all orders (even if they donâ€™t have items).
* The second gives all items (even if they arenâ€™t linked to an order).
* `UNION` combines both without duplicates.

---


---

### ðŸ†š UNION vs UNION ALL

| Feature     | `UNION`                       | `UNION ALL`                             |
| ----------- | ----------------------------- | --------------------------------------- |
| Duplicates  | Removes duplicates            | Keeps all records, including duplicates |
| Performance | Slower (due to deduplication) | Faster                                  |
| Use case    | When you want distinct data   | When you want complete raw data         |

---

### ðŸ”„ FULL OUTER JOIN using `UNION ALL` (if needed)

```sql
SELECT
    o.order_id,
    o.customer_id,
    oi.product_id,
    oi.quantity
FROM orders o
LEFT JOIN order_items oi
ON o.order_id = oi.order_id

UNION ALL

SELECT
    o.order_id,
    o.customer_id,
    oi.product_id,
    oi.quantity
FROM orders o
RIGHT JOIN order_items oi
ON o.order_id = oi.order_id
WHERE o.order_id IS NULL; -- avoid duplicates from LEFT join
```

 **Why the WHERE clause?**
Because `UNION ALL` includes all rows, we add a filter to the second query to include **only unmatched right-side rows**.

---