
---

##  `ALTER TABLE` — Overview

###  What Can You Do with `ALTER`?

You can:

1. **Add** columns
2. **Modify** columns
3. **Rename** columns
4. **Drop** (remove) columns
5. **Add / Drop constraints** (like `PRIMARY KEY`, `FOREIGN KEY`, `UNIQUE`)
6. **Rename** the table

---

##  Examples of `ALTER` Usage

---

###  1. Add a Column

```sql
ALTER TABLE Employees
ADD date_of_joining DATE;
```

 Adds a new column `date_of_joining` to the `Employees` table.

---

###  2. Modify a Column

```sql
ALTER TABLE Employees
MODIFY name VARCHAR(150);
```

 Changes the data type or size of the `name` column.

*(In some databases like PostgreSQL, use `ALTER COLUMN name TYPE VARCHAR(150)` instead.)*

---

###  3. Rename a Column (MySQL 8+)

```sql
ALTER TABLE Employees
RENAME COLUMN name TO full_name;
```

 Renames the column from `name` to `full_name`.

---

###  4. Drop a Column

```sql
ALTER TABLE Employees
DROP COLUMN date_of_joining;
```

 Removes the `date_of_joining` column from the table.

---

###  5. Add a Foreign Key

```sql
ALTER TABLE Employees
ADD CONSTRAINT fk_dept
FOREIGN KEY (dept_id) REFERENCES Departments(dept_id);
```

 Adds a foreign key constraint to ensure `dept_id` in `Employees` exists in `Departments`.

---

###  6. Drop a Foreign Key (MySQL)

```sql
ALTER TABLE Employees
DROP FOREIGN KEY fk_dept;
```

 Removes the foreign key constraint named `fk_dept`.

>  Note: To drop a constraint, you **must know its name**.

---

###  7. Rename a Table

```sql
ALTER TABLE Employees
RENAME TO Staff;
```

 Changes the table name from `Employees` to `Staff`.

---


---

##  Example 1: Drop a **Foreign Key Constraint**

Let’s say you have a foreign key on `dept_id` in the `staff` table, and its constraint name is `fk_dept`.

###  Step 1: Drop the Foreign Key

```sql
ALTER TABLE staff
DROP FOREIGN KEY fk_dept;
```

---

##  Example 2: Drop a **Unique Constraint**

Suppose your `Users` table has a unique constraint on the `email` column, and its constraint name is `email_unique`.

###  Step 1: Drop the Unique Constraint

```sql
ALTER TABLE Users
DROP INDEX email_unique;
```

>  In MySQL, **UNIQUE** constraints are implemented as **indexes**, so we use `DROP INDEX`.

---

##  Example 3: Drop a **Check Constraint** (MySQL 8.0+)

Say your `Employees` table has a `CHECK` constraint on `age` like `CHECK (age >= 18)`, and the system named it `age_check`.

###  Step 1: Drop the Check Constraint

```sql
ALTER TABLE Employees
DROP CHECK age_check;
```

>  You must know the name of the check constraint. Use `SHOW CREATE TABLE Employees` to find it.

---

## How to Find Constraint Names

Use this query for MySQL:

```sql
SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM information_schema.TABLE_CONSTRAINTS
WHERE TABLE_NAME = 'your_table_name';
```

---