### Use the product_db.sql for this exercise

---

##  Sorting Data in SQL

###  Description:

SQL allows sorting of query results using the `ORDER BY` clause. By default, it sorts in **ascending order** (`ASC`). You can also sort in **descending order** (`DESC`). Sorting can be done by one or more columns, including **expressions**, **aliases**, and **positions**.

---

###  Syntax:

```sql
SELECT column1, column2, ...
FROM table_name
ORDER BY column1 [ASC | DESC], column2 [ASC | DESC], ...;
```

---

###  Examples using `products` Table

Assume this structure:

| Column     | Description         |
| ---------- | ------------------- |
| `name`     | Product name        |
| `price`    | Product price       |
| `discount` | Discount percentage |

---

### 1. **Sort by One Column**

#### Sort by `price` in ascending order (default)

```sql
SELECT name, price
FROM products
ORDER BY price;
```

#### Sort by `price` in descending order

```sql
SELECT name, price
FROM products
ORDER BY price DESC;
```

---

### 2. **Sort by Multiple Columns**

Sort by `discount` first, then `price` (both ascending):

```sql
SELECT name, discount, price
FROM products
ORDER BY discount, price;
```

Sort by `discount` descending, then `price` ascending:

```sql
SELECT name, discount, price
FROM products
ORDER BY discount DESC, price ASC;
```

---

### 3. **Sort by Column Position**

In this case, the position refers to the columnâ€™s order in the `SELECT` clause:

```sql
SELECT name, discount, price
FROM products
ORDER BY 2 DESC; -- Sort by discount
```

---

### 4. **Sort by Expression**

Sort by discounted price (price - discount):

```sql
SELECT name, price, discount, (price - discount) AS final_price
FROM products
ORDER BY final_price;
```

---

### 5. **Sort by Alias**

You can use the alias defined in the `SELECT` clause to sort:

```sql
SELECT name, price, discount, (price - discount) AS net_price
FROM products
ORDER BY net_price DESC;
```

---

### 6. **Combining with WHERE**

```sql
SELECT name, price
FROM products
WHERE price > 1000
ORDER BY price DESC;
```

---