"""
# Introduction to Pandas Series

This notebook provides an introduction to Pandas Series, a fundamental data structure in Pandas.
"""

In [2]:
# Importing Pandas
import pandas as pd


"""
## Creating a Pandas Series
A Pandas Series is a one-dimensional labeled array capable of holding any data type.
"""

In [3]:
# Creating a Series from a list
data = [10, 20, 30, 40, 50]
series1 = pd.Series(data)
print("Series from a list:")
print(series1)

Series from a list:
0    10
1    20
2    30
3    40
4    50
dtype: int64


### Adding Custom Index Labels
We can specify custom labels for the indices.

In [ ]:
index_labels = ['a', 'b', 'c', 'd', 'e']
series2 = pd.Series(data, index=index_labels)
print("Series with custom index labels:")
print(series2)

### Creating a Series from a Dictionary
A dictionary can be used to create a Series where keys become the index labels.

In [ ]:
data_dict = {'Alice': 85, 'Bob': 90, 'Charlie': 78, 'David': 92}
series3 = pd.Series(data_dict)
print("Series from a dictionary:")
print(series3)


## Accessing Elements in a Series
You can access elements using index labels or positions.

In [ ]:
# Accessing by position
print("Element at position 2:", series1[2])

# Accessing by index label
print("Score of Bob:", series3['Bob'])

## Performing Operations on a Series
Series support vectorized operations like NumPy arrays.

In [4]:

print("Adding 10 to each element:")
print(series1 + 10)

print("Multiplying each element by 2:")
print(series1 * 2)

Adding 10 to each element:
0    20
1    30
2    40
3    50
4    60
dtype: int64
Multiplying each element by 2:
0     20
1     40
2     60
3     80
4    100
dtype: int64

## Filtering Data in a Series
We can filter values based on conditions.

Series from a list:
0    10
1    20
2    30
3    40
4    50
dtype: int64
Series with custom index labels:
a    10
b    20
c    30
d    40
e    50
dtype: int64
Series from a dictionary:
Alice      85
Bob        90
Charlie    78
David      92
dtype: int64
Element at position 2: 30
Score of Bob: 90
Adding 10 to each element:
0    20
1    30
2    40
3    50
4    60
dtype: int64
Multiplying each element by 2:
0     20
1     40
2     60
3     80
4    100
dtype: int64
Values greater than 20:
2    30
3    40
4    50
dtype: int64
Series with NaN values:
0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64
Filling NaN with default value:
0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
dtype: float64
Basic statistics of series1:
count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

"""
### Adding Custom Index Labels
We can specify custom labels for the indices.
"""